services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SERVER_PORT: 8088
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5436/workload_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: changemeinprod!
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5436/workload_db
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: changemeinprod!
    depends_on:
      - db
    restart: always

  db:
    image: "postgres:15-alpine"
    ports:
      - "5436:5436"
    environment:
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: workload_db
      POSTGRES_USER: postgres
    command: postgres -p 5436
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data1:
